import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Perfumes from '../pages/api/PerfumesJSON.js'
import PerfumeCard from '../components/PerfumeCard'

export default function Home() {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Perfumes Arian</title>
        <meta name="description" content="Generated by create-next-app by Frank Perez" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className='Catalogue'>
          {Perfumes.map(perfume => {
              return <PerfumeCard key={perfume.id} perfume={perfume}/>
          })}
        </div>
      </main>

      <footer>
        
      </footer>
    </div>
  )
}
