import Head from 'next/head'
import Products from '../pages/api/ProductsJSON.js'
import ProductCard from '../components/ProductCard'

export default function Home() {
  
  return (
    <div >
      <Head>
        <title>Products Template</title>
        <meta name="description" content="Generated by create-next-app by Frank Perez" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className='Catalogue'>
          {Products.map(product => {
              return <ProductCard key={product.id} product={product}/>
          })}
        </div>
      </main>

      <footer>
        
      </footer>
    </div>
  )
}
